name: Build & Test

on:
  push:
    branches:    
      - '**' # matches every branch  
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WizardsoftGitHubToken }}
        fetch-depth: 0
        submodules: 'recursive'
        
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
        
    - name: Display GitVersion config
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml  

    - name: Display GitVersion outputs
      run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"        
        
    - name: Restore dependencies
      run: dotnet restore src/GoodSign.NetStandard.sln
      
    - name: Build
      run: dotnet build src/GoodSign.NetStandard.sln --no-restore

    # create a NuGet package from files in the "reports" folder; create package in "packaging" folder
    - name: Pack
      run: dotnet pack src/GoodSign.NetStandard/GoodSign.NetStandard.csproj -p:Version=${{ steps.gitversion.outputs.fullSemVer }} --no-build --output .
        
    # Publish the NuGet package as an artifact, so they can be used in the following jobs
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: nuget
    #     if-no-files-found: error
    #     retention-days: 7
    #     path: packaging/*.nupkg        