name: Build & Test

on:
  push:
    branches:    
      - '**' # matches every branch  
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WizardsoftGitHubToken }}
        fetch-depth: 0
        submodules: 'recursive'
        
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
        
    - name: Display GitVersion config
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml  

    - name: Display GitVersion outputs
      run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"        
        
    - name: Restore dependencies
      run: dotnet restore src/GoodSign.NetStandard.sln
      
    - name: Build
      run: dotnet build src/GoodSign.NetStandard.sln --no-restore

    # create a NuGet package from files in the "reports" folder; create package in "packaging" folder
    - name: Create a NuGet package 🐙
      uses: OctopusDeploy/create-nuget-package-action@v3
      with:
        package_id: 'GoodSign.NetStandard'
        version: ${{ steps.gitversion.outputs.fullSemVer }}
        output_folder: 'packaging'
        base_path: src
        files: |
          GoodSign.NetStandard/*.csproj
        nuspec_description: |
          Allows you to programatically interface with the GoodSign.io API. API Docs here: https://goodsign.io/api/help
        nuspec_authors: Recruit Wizard           